### ISSUE TITLE
Using absolute paths

### ISSUE THREAD

**Issue by mokagio** [schwa/punic#11]
Hi @schwa :wave:

When running `punic build` to build a framework with nested dependencies, the symlinked `Carthage/Build` folder is created using an absolute rather than relative path.

With _nested dependencies_ I am referring to a framework that depends on other frameworks, and defines them in its `Cartfile`. For example [BrightFutures](https://github.com/Thomvis/BrightFutures) depends on [Result](https://github.com/antitypical/Result). In terms of `Cartfile`s:

```
# Project Cartfile
github "Thomvis/BrightFutures"

# Project Cartfile.resolved
github "antitypical/Result" "2.1.3"
github "Thomvis/BrightFutures" "v4.1.1"
```

I created [this repo](https://github.com/mokagio/carthage-punic-diff) to showcase the issue better.

As you can see [in this diff](https://github.com/mokagio/carthage-punic-diff/commit/267cfdf42694d08b100d7158ed3b9928a92b74c4) the `Carthage/Build` symlink created by the build process changed and is now using an absolute path.

My understanding of why the symlink is there is so that BrightFutures can build. That is because BrigthFutures depends on Result and expects it to be located in its own `Carthage/Build` folder.

**Comment by schwa** [comment]
Interesting. Thanks for the test repo - I'm spending a few days this week improving Punic - and the test repo will certainly make it easier to view the problem.

**Comment by schwa** [comment]
Is this an xcode 8 or 7 project?
