### ISSUE TITLE
Beta dependency versions not being resolved correctly

### ISSUE THREAD

**Issue by tonyarnold** [schwa/punic#13]
Given the following `Cartfile`: 

```
github "SwiftBond/Bond" ~> 5.0
```

When I run `punic fetch` against this, rather than fetching Bond `v5.0.0-beta6`, punic resolves `v5.0.0-beta1` (and similarly for it's dependency ReactiveKit, it's resolving the older `v3.0.0-beta3` release, rather than the correct `v3.0.0-beta5`).

`Cartfile.resolved` looks like this after running punic:

```
github "ReactiveKit/ReactiveKit" "v3.0.0-beta3"
github "SwiftBond/Bond" "v5.0.0-beta1"
```

And like this after running Carthage:

```
github "ReactiveKit/ReactiveKit" "v3.0.0-beta5"
github "SwiftBond/Bond" "v5.0.0-beta6"
```

**Comment by schwa** [comment]
Yeah it looks like I totally neglected to implement the semantic version "tags". My bad. I'll have this in today.

**Comment by schwa** [comment]
Ok - update punic to 0.1.20 and take a go.

**Comment by tonyarnold** [comment]
Works a treat, thanks @schwa!
