### ISSUE TITLE
fetch command fails to checkout dependency contents into Carthage/Checkouts

### ISSUE THREAD

**Issue by angelodipaolo** [schwa/punic#19]
## Steps to Reproduce
- Clone [this sample repo](https://github.com/angelodipaolo/PunicFetchTest) that contains a Cartfile with a single dependency but no Cartfile.resolved.
- Run `punic resolve`
- Run `punic fetch`
## Result

Punic fails to checkout the contents of the dependencies into the Carthage/Checkout directory. An empty Carthage/Builds directory is created (which is expected since it should not build the dependencies) but the contents of the dependencies are not checked out.

It's worth noting that this same behavior is also reproducible by running `punic resolve --fetch`.
## Expected

Punic should checkout the contents of the dependencies into the Carthage/Checkout directory.

**Comment by schwa** [comment]
I do want to fix this but believe it will take an afternoon or so. It's the next fix I plan on addressing though.
