### ISSUE TITLE
Incorrect punic resolve output.

### ISSUE THREAD

**Issue by calebd** [schwa/punic#22]
A cart file with `github "facebook/facebook-ios-sdk"` fails to select the correct versions or dependencies after running `punic resolve`.

Cartfile: 

```
github "facebook/facebook-ios-sdk"
```

Expected Cartfile.resolved:

```
github "BoltsFramework/Bolts-ObjC" "1.8.4"
github "facebook/facebook-ios-sdk" "sdk-version-4.17.0"
```

Actual Cartfile.resolved:

```
github "facebook/facebook-ios-sdk" "v1.2"
```

**Comment by schwa** [comment]
Yup. Serious bug. Looking into...

**Comment by schwa** [comment]
OK - this is fixed on master. You can test it with `pip install -U git+https://github.com/schwa/punic`

**Comment by calebd** [comment]
Awesome, thanks!
