### ISSUE TITLE
Dependencies should be case insensitive.

### ISSUE THREAD

**Issue by calebd** [schwa/punic#23]
It looks like multiple declarations of the same dependencies with different capitalizations (and different version) results in multiple entries for the same dependency in `Cartfile.resolved`.

This input:

```
github "ReactiveCocoa/ReactiveSwift"
github "AntiTypical/result"
```

results in this output:

```
github "AntiTypical/result" "3.0.0-alpha.4"
github "ReactiveCocoa/ReactiveSwift" "1.0.0-alpha.3"
github "antitypical/Result" "3.0.0-alpha.4"
```

because ReactiveSwift declares Result as a dependency with a different capitalization. Additionally, if the above `Cartfile` specified a different (yet still compatible) version of Result than ReactiveSwift does, the duplicate entries in the resolve file will have different versions.

**Comment by schwa** [comment]
Good catch.

**Comment by calebd** [comment]
Thanks for fixing these so quickly!
