### ISSUE TITLE
Punic attempts to build non-framework target.

### ISSUE THREAD

**Issue by calebd** [schwa/punic#27]
Punic version: 0.2.4
Command: punic build --no-fetch --platform ios
Cartfile: github "realm/realm-cocoa" ~> 2.1.0
Cartfile.resolved: github "realm/realm-cocoa" "v2.1.0"

Output:

```
$ punic build --dry-run --no-fetch --platform ios
Build
Using xcode version: /Applications/Xcode-8.1.0.app (8.1)
DRY-RUN: (Not) Building: Realm.xcodeproj (scheme: Object Server Tests, sdk: iphoneos, configuration: None)...
DRY-RUN: (Not) Building: Realm.xcodeproj (scheme: Object Server Tests, sdk: iphonesimulator, configuration: None)...
DRY-RUN: (Not) Building: Realm.xcodeproj (scheme: Realm, sdk: iphoneos, configuration: None)...
DRY-RUN: (Not) Building: Realm.xcodeproj (scheme: Realm, sdk: iphonesimulator, configuration: None)...
DRY-RUN: (Not) Building: Realm.xcodeproj (scheme: RealmSwift, sdk: iphoneos, configuration: None)...
DRY-RUN: (Not) Building: Realm.xcodeproj (scheme: RealmSwift, sdk: iphonesimulator, configuration: None)...
```

Punic is unable to build the "Object Server Tests" for reasons I cannot determine. Carthage skips this scheme entirely. It is a scheme that builds multiple targets, including at least one dynamic framework so I understand why punic sees it as a potential scheme.

I can work around this temporarily by adding it to a skip list.

**Comment by calebd** [comment]
Hm I might be wrong on this one. Carthage builds a bunch of the targets multiple times. It used to do that anyway but that was fixed. I now suspect that this is a realm project issue. Going to look into this further.

**Comment by schwa** [comment]
Realm has a very idiosyncratic project file. I added skip lists to punic _for_ realm…

**Comment by schwa** [comment]
Looking at Realm's structure and the build settings I'm not sure I can easily detect that the `Object Server Tests` scheme is not the scheme that we want to build. I'd suggest using a skip list as you're already doing and/or filing an issue with Realm.

Curious to what you find with Carthage though.

Feel free to make this as closed if you're ok with "use skip lists" as an answer.

**Comment by calebd** [comment]
Ok I did some digging and opened realm/realm-cocoa#4375 since there seems to be a project structure issue. Adding the "Object Server Tests" to a skip list combined with punic implicitly skipping the contents of the RealmExamples workspace does solve the problem and makes punic builds much faster than carthage. I am ok with that solution for now. Thanks!
