### ISSUE TITLE
Support branch based version requirements

### ISSUE THREAD

**Issue by jamiepinkham** [schwa/punic#35]
Currently, Carthage supports the following for version requirements: 

```
Carthage supports several kinds of version requirements:

>= 1.0 for “at least version 1.0”
~> 1.0 for “compatible with version 1.0”
== 1.0 for “exactly version 1.0”
"some-branch-or-tag-or-commit" for a specific Git object (anything allowed by git rev-parse)
```

And it appears that `punic` only supports tags. It'd be nice if `punic` could support any Git object as a version requirement, much like `Carthage` does

**Comment by schwa** [comment]
Punic supports all four version requirements. Will look at updating the docs if that's not clear.

**Comment by jamiepinkham** [comment]
Perfect, thanks for the clarification!
