### ISSUE TITLE
Siesta framework building

### ISSUE THREAD

**Issue by leoMehlig** [schwa/punic#39]
The [Siesta](https://github.com/bustoutsolutions/siesta) has one scheme that somehow creates two .framework file: `Siesta.framework` and `SiestaUI.framework` when I build it with `carthage`, but with Punic it only produces the `SiestaUI` framework. 

**Cartfile**
```
github "hyperoslo/Whisper"
github "onevcat/Kingfisher"
github "marmelroy/PhoneNumberKit"
github "marmelroy/Interpolate"
github "Alamofire/Alamofire"
github "mxcl/PromiseKit"
github "realm/realm-cocoa" ~> 2.1
github "bustoutsolutions/siesta"
github "JohnSundell/Unbox"
```

**Cartfile.resolved**
```
github "Alamofire/Alamofire" "4.2.0"
github "marmelroy/Interpolate" "0.4.0"
github "onevcat/Kingfisher" "3.2.4"
github "marmelroy/PhoneNumberKit" "1.2.1"
github "mxcl/PromiseKit" "4.1.3"
github "JohnSundell/Unbox" "2.3.0"
github "hyperoslo/Whisper" "4.0.0"
github "realm/realm-cocoa" "v2.1.2"
github "bustoutsolutions/siesta" "1.0.1"
``` 

Sorry for all the issues, but I trying to switch to punic since Carthage is very slow for our setup, especially on the CI machine. If I can help somehow pls tell me, but since I don't have a lot of python experience I can't quite debug the code. Maybe there is some sort of starter task?!  😊

**Comment by leoMehlig** [comment]
I've check the build folder and the `Siesta.framework` file is there, but it doesn't get copied over to the `Carthage/Build/iOS` folder. The path to the `Siesta.framework` folder also doesn't appear in the build output. Maybe all the file from the build output folders have to get copied/moved into the `Carthage` folder?!

**Comment by schwa** [comment]
Yeah you seem to have nailed it. Looking into this. It could be the code assumes one scheme = one build product.

Siesta has two build products for the iOS scheme. As you pointed out they both build.

**Comment by schwa** [comment]
So yeah that's the problem. Code stupidly believes that one build of a scheme = 1 build product. unfortunately xcodebuild isn't necessarily able to give us the info we need. It only returns the data for one of the builds (I presume the first).

Will try and find a good solution for this.

**Comment by schwa** [comment]
OK https://github.com/schwa/punic/tree/jwight/issue_39 seems to fix it. It complicates the post processing step quite a lot but I don't think it should cause issues. I'll test this well before merging into master. Thanks for finding a pretty serious bug!
