### ISSUE TITLE
Punic cache filename hashing

### ISSUE THREAD

**Issue by jasontrademark** [schwa/punic#44]
Punic cache uses, among other things, `swift -version` to generate the cache filename. Unfortunately this means that a slight mismatch in Xcode versions will prevent the cache from working on one end. For example, we use Xcode 8.2.1 which reports Swift version 3.0.2, but TravisCI only has Xcode 8.2 and Swift 3.0.1.

Swift doesn't yet have ABI stability, so generally this mismatch should be the correct outcome. However, 3.0.1 and 3.0.2 are so close to identical it would be nice to be able to live dangerously when we believe it to be reasonably safe.

**Comment by schwa** [comment]
Unfortunately changing this would break all existing caches in existence.

If you can provide an implementation that doesn't have this property I'd consider it :-)
