### ISSUE TITLE
[Bug]revisions_for_predicate returns empty array

### ISSUE THREAD

**Issue by CodeEagle** [schwa/punic#58]
I have a repo that tags [1.0.1, 1.0.0]
then run `revisions_for_predicate` that suits `~> 0.9.2`
will get empty return 
```
def revisions_for_predicate(self, predicate):
        # type: (VersionPredicate) -> [Tag]
        listTags = list(set(self.tags))
        #        logging.info('self.tags:{}'.format(listTags))
        ret = [tag for tag in listTags if predicate.test(tag.semantic_version)]
        if ret:
            return ret
        else:
            return [listTags[0]]
```

**Comment by schwa** [comment]
Yes. Jumping from 0.9 to 1.0 implies there might be breaking changes. ~> 0.9.2 would mean any version compatible with 0.9.2 (e.g. 0.9.3 to < 1.0). See https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfile for more

**Comment by CodeEagle** [comment]
look at this:
      A ~> 0.9.2
then,  `A` depend on `B`, `B` tags `[1.0.1, 1.0.0]`
when update A, B got no tags

**Comment by schwa** [comment]
I'm not quite sure I understand what you're saying there.

Quite simply ~> is the "comparability operator". 1.0.x is not compatible with 0.9.x. See this line in the link I provided above: "Only patch versions are compatible under 0.x, meaning 0.1.1 is compatible with 0.1.2, but not 0.2."

Punic Cartfile support is based on Carthage's definition of Cartfiles. If you find that Punic is NOT working the same as Carthage in regards to version resolution please file a bug here.

**Comment by CodeEagle** [comment]
dependency
```
A.git  ~> 0.9.2
    |_ B.git [1.0.1, 1.0.0]
```

`A` depend on `B`

run `punic update`, will assert B tags `[]`

**Comment by CodeEagle** [comment]
Carfile `Main`

```
git "git@github.com:XXX/A.git" ~> 0.9.2
```

Carfile `A`

```
git "git@github.com:XXX/B.git"
```
repo `A` has tags [0.9.1, 0.9.2], repo `B` has tags [1.0.1, 1.0.0]

run `punic update`,  `B` will get no tags available
